<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>ai.typesafe</groupId>
    <artifactId>typesafe-sdk-parent</artifactId>
    <version>0.6.0</version>
  </parent>

  <artifactId>typesafe-sample</artifactId>
  <name>TypeSafe Java SDK sample</name>

  <properties>
    <maven.deploy.skip>true</maven.deploy.skip>
    <exec.skip>false</exec.skip>
  </properties>

  <dependencies>
    <dependency>
      <groupId>ai.typesafe</groupId>
      <artifactId>typesafe-sdk</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
